version: '3.9'

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: mongodb://mongo:27017/gym-saas
      JWT_ACCESS_SECRET: change_this_access_secret
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_SECRET: change_this_refresh_secret
      JWT_REFRESH_EXPIRES_IN_SHORT: 1d
      JWT_REFRESH_EXPIRES_IN_LONG: 30d
      CLIENT_ORIGIN: http://localhost:5173
    depends_on:
      mongo:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      API_PROXY_TARGET: http://backend:3000
    ports:
      - '5173:5173'
    depends_on:
      - backend

volumes:
  mongo-data:
